version: '3'
services:
    servant-tutorial:
        build: .
        image: servant-tutorial
        command: servant-tutorial
        expose:
            - "1234"
    nginx:
        build: ./nginx
        image: nginx
        ports:
            - "8080:80"
        depends_on:
            - servant-tutorial
